### ISSUE TITLE
Examples of building + deploying end-to-end ML Apps

### ISSUE THREAD

**Issue by krmiddlebrook** [BreakoutMentors/Data-Science-and-Machine-Learning#17]
## Why
We want to provide students with tutorials that demonstrate how to build an ML App that can be used by / shown to others, i.e., how to build an ML model, package it, and then deploy it as an app that others can use.

### Breakdown
Explain your approach to implementing the change. Include the changes you will be making in each repository.
- [ ] Data-Science-and-Machine-Learning
  - [x] Tutorial in Colab showing how to deploy ML apps with Gradio.
  - [x] Create a challenge in Colab that uses a pre-trained model and asks the student to deploy the model as an ML app using Gradio.
  - [ ] Create a mini-lesson showing how to create a GitHub account and create a public repository.
  - [ ] Tutorial showing how to deploy ML apps with [Streamlit](https://docs.streamlit.io/en/stable/deploy_streamlit_app.html). 
    - [ ] Tutorial should walk through creating the GitHub repo for the app, writing python scripts for the app, and deploying it to streamlit (for free!). 
  - [ ] Create a streamlit challenge that requires the student to create a GitHub repo, write a python script with ML pre-trained model + streamlit app code, and deploy their app using streamlit.

### QA Plan
Steps you will follow locally and on the cloud to verify expected behavior of all affected areas.
- [ ] @krmiddlebrook & @bskinny129  test the demo apps

**Comment by krmiddlebrook** [comment]
How to host a permanent ML app with Gradio: [gradio hosting](https://gradio.app/introducing-hosted).

**Comment by krmiddlebrook** [comment]
How to host a permanent ML app with Streamlit (free!!): [streamlit hosting](https://docs.streamlit.io/en/stable/deploy_streamlit_app.html).
