### ISSUE TITLE
Add/extend basics resources (OOP + data manipulation and visualization)

### ISSUE THREAD

**Issue by krmiddlebrook** [BreakoutMentors/Data-Science-and-Machine-Learning#26]
## Why
We want to add/extend the basics resources (the tutorials/reviews of OOP + data manipulation and visualization) to make it easier for our younger/beginner students to learn the data science skills they'll use in the later lessons of the  ML Deep Dive curriculum. 

### Breakdown
Explain your approach to implementing the change. Include the changes you will be making in each repository. 
- [x] Data-Science-and-Machine-Learning (All tutorials/challenges should be coded in Colab notebooks).
  - [x] Add brief tutorial/review on OOP in Python. Make sure to cover the following:
    - [x] Importing libraries
    - [x] Defining variables + changing their values
    - [x] Examples of different primitive data types (str, int, float, list, set, dict)
    - [x] Iterating/Looping over collections (i.e., lists, sets, and dicts)
    - [x] Defining a class + instantiating a class.
    - [x] Class inheritance, i.e., defining a parent class and using `super()` in a child class.
  - [x]  Create a challenge/exercise for OOP in Python.
  - [x] Create a challenge/exercise for data manipulation with Numpy (if needed, you can also extend the existing Numpy basics tutorial).
  - [x] Create a challenge/exercise for data manipulation with Pandas (if needed, you can also extend the existing Pandas basics tutorial).
  - [x] Create a challenge/exercise for data visualization with Matplotlib (if needed, you can also extend the existing Matplotlib basics tutorial).

### QA Plan
Steps you will follow locally and on the cloud to verify the expected behavior of all affected areas.
- [ ] Review materials with @krmiddlebrook.

### Post Release
Non destructive QA we can perform post release to verify things are working.
- [ ] Use the material with our younger/beginner ML students.
