### ISSUE TITLE
Expand Building ML Apps section

### ISSUE THREAD

**Issue by krmiddlebrook** [BreakoutMentors/Data-Science-and-Machine-Learning#33]
## Why
There are many free and easy-to-use yet powerful tools for creating interactive demos for your ML models. We want to provide more resources/examples for our students that showcase how to they can use these tools.

### Breakdown
Explain your approach to implementing the change. Include the changes you will be making in each repository.
- [ ] Data-Science-and-Machine-Learning: Building ML Apps 
  - [ ] Creating a github repository. 
  - [ ] Getting started with 🤗 Hugging Face Spaces.
  - [ ] Getting started with Streamlit.

### QA Plan
Steps you will follow locally and on the cloud to verify expected behavior of all affected areas.
- [ ] ∞

### Post Release
Non destructive QA we can perform post release to verify things are working.
- [ ] ∞
